# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  # This is just an example; adjust the paths and extensions as needed.

[log]
  time_format = "15:04:05"
  text = "changed"

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
